/*
 * PIN CHANGE INTERRRUPT PROGRAM, REGISTER LEVEL PROGRAMMING
 * 
 * REGISTERS USED :
 * 
 *      SREG : STATUS REGISTER : TO CONTROL GLOBAL INTERRUPT FLAG
 *      
 *      PCICR : PIN CHANGE INTERRUPT CONTROL REGISTER : ENABLES INTERRRUPT ON GROUP OF I/O PINS
 *      
 *      PCMSK2: PIN CHANGE MASK REGISTER : ENABLES INTERRUPT ON INDIVIDUAL PINS
 *      
 *      DDRB : DATA DIRECTION REGISTER OF PORT B : SETTING 8 AS OUTPUT PIN
 *      
 *      PORTB : PORT REGISTER OF PORT B : SETS 1 OR 0 IN PIN 8
 * 
 */

void setup() {
  // put your setup code here, to run once:

    //SETTING OUTPUT PIN, PIN 8
    DDRB |= (1<<DDB0);

    //SETTING GLOBAL INTERRUPT REGISTER
    SREG |= (1<<7);

    //PIN CHANGE INTERRUPT CONTROL REGISTER, ENABLES ALL PINS FOR INTERRUPT
    PCICR |= (1<<PCIE2);

    //PCMSK2: PIN CHANGE MASK REGISTER 2
    
    PCMSK2 |= (1<<PCINT23);
    
    
  
}

void loop() {
  // put your main code here, to run repeatedly:

}

//INTERRUPT SERVICE ROUTINE
ISR(PCINT2_vect){

    PORTB ^= (1<<PB0);
  
}
